In [33]:
#QUESTION 1
import numpy as n
arr =n.random.random((12,5))
print(arr)
print('The last row of the array is:',arr[11:12])
arr[11]=[1.78,2.56,3.333,4.43,5.8796]
print('After updating the last row array becomes:',arr)



[[0.37132203 0.52610541 0.96023185 0.39971742 0.03217921]
 [0.06440704 0.60198291 0.74891371 0.01687585 0.65832947]
 [0.73662444 0.174902   0.44948927 0.96320052 0.19621467]
 [0.04606857 0.0192748  0.26393446 0.75844431 0.25187531]
 [0.99365697 0.31095433 0.26169402 0.54241008 0.45735003]
 [0.60927919 0.55243336 0.63386736 0.81212404 0.46497178]
 [0.1040956  0.22234908 0.7922576  0.52342795 0.79708478]
 [0.6167696  0.91071301 0.47613066 0.85786709 0.377809  ]
 [0.2816667  0.66603419 0.69022958 0.59932598 0.77740247]
 [0.88062916 0.24649851 0.48877928 0.26160004 0.45363706]
 [0.63209298 0.42415692 0.81029242 0.02016428 0.82912053]
 [0.64122476 0.45632363 0.67826695 0.46004876 0.88568918]]
The last row of the array is: [[0.64122476 0.45632363 0.67826695 0.46004876 0.88568918]]
After updating the last row array becomes: [[0.37132203 0.52610541 0.96023185 0.39971742 0.03217921]
 [0.06440704 0.60198291 0.74891371 0.01687585 0.65832947]
 [0.73662444 0.174902   0.44948927 0.96320052 0.1962146

In [29]:
#QUESTION 2
arr2 = n.random.randint(1,60,60)
print(arr2)
arr3=arr2.reshape(12,5)
print(arr3)
i =0
for row in arr3:
    print('The maximun value in row ',i,':',max(row))
    print('The minimum value in row ',i,':',min(row))
    i+=1

[25 38 21  6 28 12 51 53  5 47  6 20 33 10 32 30 37 22 15 40 11 25 25 20
 55 43 48 11 58 50 40 37 29 40  3 45 50 43 45 30 49 18 29 46  5 17 22 53
 38 19 35 40 19 42  4 16 51 56 40 44]
[[25 38 21  6 28]
 [12 51 53  5 47]
 [ 6 20 33 10 32]
 [30 37 22 15 40]
 [11 25 25 20 55]
 [43 48 11 58 50]
 [40 37 29 40  3]
 [45 50 43 45 30]
 [49 18 29 46  5]
 [17 22 53 38 19]
 [35 40 19 42  4]
 [16 51 56 40 44]]
The maximun value in row  0 : 38
The minimum value in row  0 : 6
The maximun value in row  1 : 53
The minimum value in row  1 : 5
The maximun value in row  2 : 33
The minimum value in row  2 : 6
The maximun value in row  3 : 40
The minimum value in row  3 : 15
The maximun value in row  4 : 55
The minimum value in row  4 : 11
The maximun value in row  5 : 58
The minimum value in row  5 : 11
The maximun value in row  6 : 40
The minimum value in row  6 : 3
The maximun value in row  7 : 50
The minimum value in row  7 : 30
The maximun value in row  8 : 49
The minimum value in row  8 : 5
The maximu